In [1]:

# Imports
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
from sqlalchemy import create_engine



# 2. Create MySQL Engine

engine = create_engine(
      "mysql+pymysql://churn_model:Nikhil%40123@localhost:3306/churnAnalysis"
)



# 3. Read CSV File
data = pd.read_csv("churn dataset.csv")

# 4. Load Data into MySQL
data.to_sql(
    name="churn_data",        
    con=engine,
    if_exists="replace", 
    index=False          
)


print("✅ CSV successfully loaded into MySQL table 'churnAnalysis'")

✅ CSV successfully loaded into MySQL table 'churnAnalysis'

In [2]:
pd.read_sql("SELECT COUNT(*) FROM churn_data", engine)

   COUNT(*)
0    440833

In [3]:
df=pd.read_csv("churn dataset.csv")

In [4]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [5]:
df.isnull().sum()

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [6]:
df.describe()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000
mean,225398.667955,39.373153,31.256336,15.807494,3.604437,12.965722,631.616223,14.480868,0.567107
std,129531.918550,12.442369,17.255727,8.586242,3.070218,8.258063,240.803001,8.596208,0.495477
min,2.000000,18.000000,1.000000,1.000000,0.000000,0.000000,100.000000,1.000000,0.000000
25%,113621.750000,29.000000,16.000000,9.000000,1.000000,6.000000,480.000000,7.000000,0.000000
50%,226125.500000,39.000000,32.000000,16.000000,3.000000,12.000000,661.000000,14.000000,1.000000
75%,337739.250000,48.000000,46.000000,23.000000,6.000000,19.000000,830.000000,22.000000,1.000000
max,449999.000000,65.000000,60.000000,30.000000,10.000000,30.000000,1000.000000,30.000000,1.000000

In [7]:
df.rename(columns={
    "Usage Frequency": "usage_freq",
    "Support Calls": "support_calls",
    "Subscription Type": "plan_type",
    "Contract Length": "contract_months",
    "Last Interaction": "last_active_days"
}, inplace=True)

In [8]:
df.head(20)

,CustomerID,Age,Gender,Tenure,usage_freq,support_calls,Payment Delay,plan_type,contract_months,Total Spend,last_active_days,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0
5,8.0,51.0,Male,33.0,25.0,9.0,26.0,Premium,Annual,129.0,8.0,1.0
6,9.0,58.0,Female,49.0,12.0,3.0,16.0,Standard,Quarterly,821.0,24.0,1.0
7,10.0,55.0,Female,37.0,8.0,4.0,15.0,Premium,Annual,445.0,30.0,1.0
8,11.0,39.0,Male,12.0,5.0,7.0,4.0,Standard,Quarterly,969.0,13.0,1.0
9,12.0,64.0,Female,3.0,25.0,2.0,11.0,Standard,Quarterly,415.0,29.0,1.0
10,13.0,29.0,Male,18.0,9.0,0.0,30.0,Premium,Quarterly,930.0,18.0,1.0
11,14.0,52.0,Female,21.0,6.0,3.0,26.0,Premium,Monthly,830.0,19.0,1.0
12,15.0,22.0,Male,41.0,17.0,10.0,25.0,Basic,Quarterly,265.0,23.0,1.0
13,16.0,48.0,Female,35.0,25.0,1.0,13.0,Basic,Annual,518.0,17.0,1.0
14,17.0,24.0,Male,4.0,9.0,4.0,22.0,Standard,Quarterly,204.0,4.0,1.0
15,18.0,49.0,Male,56.0,17.0,2.0,30.0,Standard,Quarterly,975.0,17.0,1.0
16,19.0,19.0,Female,38.0,23.0,7.0,11.0,Basic,Quarterly,978.0,3.0,1.0
17,20.0,47.0,Male,41.0,14.0,1.0,5.0,Premium,Annual,151.0,19.0,1.0
18,21.0,24.0,Male,44.0,13.0,5.0,4.0,Premium,Monthly,669.0,13.0,1.0
19,22.0,42.0,Male,15.0,16.0,2.0,14.0,Premium,Quarterly,262.0,16.0,1.0

In [9]:
pd.read_sql("""
SELECT 
    COUNT(CASE WHEN churn = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS churn_rate
FROM churn_data
""", engine)

   churn_rate
0    43.28918

In [10]:
pd.read_sql("""
SELECT churn, COUNT(*) AS total_customers
FROM churn_data
GROUP BY churn
""", engine)

   churn  total_customers
0    1.0           249999
1    0.0           190833
2    NaN                1

In [11]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN COUNT(CASE WHEN churn = 'Yes' THEN 1 END) * 100.0 / COUNT(*) > 30 
        THEN 'High Churn'
        ELSE 'Low Churn'
    END AS churn_status
FROM churn_data
""", engine)

  churn_status
0   High Churn

In [12]:
print(df.columns)

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'usage_freq', 'support_calls',
       'Payment Delay', 'plan_type', 'contract_months', 'Total Spend',
       'last_active_days', 'Churn'],
      dtype='object')

In [13]:
query = (
    "SELECT `Subscription Type`, COUNT(*) AS churn_count "
    "FROM churn_data "
    "WHERE Churn = 1 "
    "GROUP BY `Subscription Type` "
    "ORDER BY churn_count DESC"
)

pd.read_sql(query, engine)

  Subscription Type  churn_count
0          Standard        83616
1             Basic        83210
2           Premium        83173

In [14]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN age < 25 THEN 'Young'
        WHEN age BETWEEN 25 AND 50 THEN 'Adult'
        ELSE 'Senior'
    END AS age_group,
    COUNT(*) AS churn_count
FROM churn_data
WHERE churn = 'Yes'
GROUP BY age_group
ORDER BY churn_count DESC
""", engine)

  age_group  churn_count
0     Adult       163182
1     Young        27651

In [15]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN tenure < 12 THEN 'New'
        ELSE 'Old'
    END AS customer_type,
    COUNT(*) AS churn_count
FROM churn_data
WHERE churn = 'Yes'
GROUP BY customer_type
""", engine)

  customer_type  churn_count
0           New        32610
1           Old       158223

In [16]:
pd.read_sql("""
SELECT tenure, COUNT(*) AS churn_count
FROM churn_data
WHERE churn = 'Yes'
GROUP BY tenure
ORDER BY tenure
""", engine)

    tenure  churn_count
0      1.0         2219
1      2.0         2320
2      3.0         2346
3      4.0         2369
4      5.0         2367
5      6.0         3580
6      7.0         3438
7      8.0         3426
8      9.0         3481
9     10.0         3549
10    11.0         3515
11    12.0         2519
12    13.0         2457
13    14.0         2401
14    15.0         2472
15    16.0         2489
16    17.0         2409
17    18.0         2406
18    19.0         2404
19    20.0         2498
20    21.0         2485
21    22.0         2453
22    23.0         2472
23    24.0         2424
24    25.0         3568
25    26.0         3477
26    27.0         3461
27    28.0         3451
28    29.0         3425
29    30.0         3458
30    31.0         3469
31    32.0         3545
32    33.0         3595
33    34.0         3489
34    35.0         3457
35    36.0         3569
36    37.0         3476
37    38.0         3514
38    39.0         3463
39    40.0         3471
40    41.0         3499
41    42.0         3508
42    43.0         3533
43    44.0         3562
44    45.0         3550
45    46.0         3503
46    47.0         3543
47    48.0         3550
48    49.0         3637
49    50.0         3536
50    51.0         3416
51    52.0         3567
52    53.0         3522
53    54.0         3444
54    55.0         3473
55    56.0         3586
56    57.0         3517
57    58.0         3490
58    59.0         3417
59    60.0         3593

In [17]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN tenure > 24 THEN 'Long'
        ELSE 'Short'
    END AS tenure_group,
    churn,
    COUNT(*) AS total
FROM churn_data
GROUP BY tenure_group, churn
""", engine)

  tenure_group  churn   total
0         Long    1.0  149402
1        Short    1.0  100597
2        Short    0.0   64499
3         Long    0.0  126334
4        Short    NaN       1

In [18]:
import pandas as pd

query = """
SELECT Tenure, AVG(`Total Spend`) AS avg_spend
FROM churn_data
GROUP BY Tenure
ORDER BY Tenure;
"""

result = pd.read_sql(query, engine)
print(result)

    Tenure   avg_spend
0      NaN         NaN
1      1.0  620.603531
2      2.0  612.282245
3      3.0  616.518367
4      4.0  617.824676
..     ...         ...
56    56.0  634.838354
57    57.0  634.766487
58    58.0  637.053961
59    59.0  631.402626
60    60.0  639.598323

[61 rows x 2 columns]

In [19]:
print(df.columns)

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'usage_freq', 'support_calls',
       'Payment Delay', 'plan_type', 'contract_months', 'Total Spend',
       'last_active_days', 'Churn'],
      dtype='object')

In [20]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN "Payment Delay" > 5 THEN 'High Delay'
        ELSE 'Low Delay'
    END AS delay_group,
    COUNT(*) AS churn_count
FROM churn_data
WHERE Churn = 1
GROUP BY delay_group
""", engine)

  delay_group  churn_count
0   Low Delay       249999

In [21]:
print(repr(query))
pd.read_sql("SHOW TABLES", engine)
pd.read_sql("DESCRIBE churn_data", engine)

'\nSELECT Tenure, AVG(`Total Spend`) AS avg_spend\nFROM churn_data\nGROUP BY Tenure\nORDER BY Tenure;\n'

                Field    Type Null Key Default Extra
0          CustomerID  double  YES        None
1                 Age  double  YES        None
2              Gender    text  YES        None
3              Tenure  double  YES        None
4     Usage Frequency  double  YES        None
5       Support Calls  double  YES        None
6       Payment Delay  double  YES        None
7   Subscription Type    text  YES        None
8     Contract Length    text  YES        None
9         Total Spend  double  YES        None
10   Last Interaction  double  YES        None
11              Churn  double  YES        None

In [22]:
pd.read_sql("""
SELECT `Subscription Type`, COUNT(*) AS churn_count
FROM churn_data
WHERE Churn = 1
GROUP BY `Subscription Type`
ORDER BY churn_count DESC
LIMIT 1
""", engine)

  Subscription Type  churn_count
0          Standard        83616

In [23]:
pd.read_sql("SELECT DISTINCT Churn FROM churn_data", engine)

   Churn
0    1.0
1    0.0
2    NaN

In [24]:
print(repr(query))

'\nSELECT Tenure, AVG(`Total Spend`) AS avg_spend\nFROM churn_data\nGROUP BY Tenure\nORDER BY Tenure;\n'

In [25]:
pd.read_sql("""
SELECT `Contract Length`, COUNT(*) AS churn_count
FROM churn_data
WHERE Churn = 1
GROUP BY `Contract Length`
""", engine)

  Contract Length  churn_count
0          Annual        81646
1         Monthly        87104
2       Quarterly        81249

In [26]:
pd.read_sql("""
SELECT SUM(`Total Spend`) AS total_revenue
FROM churn_data
""", engine)

   total_revenue
0   2.784366e+08

In [27]:
pd.read_sql("""
SELECT AVG(`Total Spend`) AS avg_revenue_per_customer
FROM churn_data
WHERE `Total Spend` IS NOT NULL
""", engine)

   avg_revenue_per_customer
0                631.616223

In [28]:
pd.read_sql("""
SELECT SUM(`Total Spend`) AS revenue_lost
FROM churn_data
WHERE Churn = 1
AND `Total Spend` IS NOT NULL
""", engine)

   revenue_lost
0  1.353208e+08

In [29]:
pd.read_sql("""
SELECT CustomerID, `Total Spend`
FROM churn_data
WHERE `Total Spend` IS NOT NULL
ORDER BY `Total Spend` DESC
LIMIT 1
""", engine)

   CustomerID  Total Spend
0      1890.0       1000.0

In [30]:
pd.read_sql("""
SELECT Churn, COUNT(*) AS total
FROM churn_data
WHERE `Total Spend` > (
    SELECT AVG(`Total Spend`) FROM churn_data
)
GROUP BY Churn
""", engine)

   Churn   total
0    1.0   98763
1    0.0  140660

In [31]:
pd.read_sql("""
SELECT *
FROM churn_data
WHERE `Total Spend` > (
    SELECT AVG(`Total Spend`) FROM churn_data
    LIMIT 10
)
""", engine)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,9.0,58.0,Female,49.0,12.0,3.0,16.0,Standard,Quarterly,821.00,24.0,1.0
2,11.0,39.0,Male,12.0,5.0,7.0,4.0,Standard,Quarterly,969.00,13.0,1.0
3,13.0,29.0,Male,18.0,9.0,0.0,30.0,Premium,Quarterly,930.00,18.0,1.0
4,14.0,52.0,Female,21.0,6.0,3.0,26.0,Premium,Monthly,830.00,19.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
239418,449993.0,49.0,Male,37.0,23.0,4.0,16.0,Standard,Annual,666.65,30.0,0.0
239419,449994.0,45.0,Male,6.0,25.0,2.0,15.0,Basic,Annual,837.00,2.0,0.0
239420,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
239421,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
239422,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0

In [32]:
pd.read_sql("""
SELECT CustomerID, `Total Spend`, Churn
FROM churn_data
WHERE `Total Spend` > (
    SELECT AVG(`Total Spend`) FROM churn_data
)
ORDER BY `Total Spend` DESC
""", engine)

        CustomerID  Total Spend  Churn
0         329962.0      1000.00    0.0
1         200782.0      1000.00    1.0
2         202254.0      1000.00    1.0
3         202615.0      1000.00    1.0
4         202855.0      1000.00    1.0
...            ...          ...    ...
239418    359462.0       631.64    0.0
239419    332582.0       631.63    0.0
239420    277127.0       631.63    0.0
239421    314528.0       631.62    0.0
239422    336675.0       631.62    0.0

[239423 rows x 3 columns]

In [33]:

pd.read_sql("""
SELECT 
    Churn,
    COUNT(*) AS total_customers
FROM churn_data
WHERE `Total Spend` > (
    SELECT AVG(`Total Spend`) FROM churn_data
)
GROUP BY Churn
""", engine)

   Churn  total_customers
0    1.0            98763
1    0.0           140660

In [34]:
df.shape

(440833, 12)

In [35]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN Tenure < 12 THEN 'Low Tenure'
        ELSE 'High Tenure'
    END AS tenure_group,
    
    CASE 
        WHEN `Payment Delay` > 5 THEN 'High Delay'
        ELSE 'Low Delay'
    END AS delay_group,
    
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) AS churned_customers,
    
    ROUND(
        SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2
    ) AS churn_rate
    
FROM churn_data
WHERE Churn IS NOT NULL
GROUP BY tenure_group, delay_group
ORDER BY churn_rate DESC
""", engine)

  tenure_group delay_group  total_customers  churned_customers  churn_rate
0   Low Tenure  High Delay            60590            37266.0       61.51
1  High Tenure  High Delay           278788           165610.0       59.40
2   Low Tenure   Low Delay            17906             8620.0       48.14
3  High Tenure   Low Delay            83548            38503.0       46.08

In [36]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN `Usage Frequency` < 20 THEN 'Low Usage'
        ELSE 'High Usage'
    END AS usage_group,
    
    CASE 
        WHEN `Support Calls` > 10 THEN 'High Support'
        ELSE 'Low Support'
    END AS support_group,
    
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) AS churned_customers,
    
    ROUND(
        SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2
    ) AS churn_rate

FROM churn_data
WHERE Churn IS NOT NULL
GROUP BY usage_group, support_group
ORDER BY churn_rate DESC
""", engine)

  usage_group support_group  total_customers  churned_customers  churn_rate
0   Low Usage   Low Support           274234           158477.0       57.79
1  High Usage   Low Support           166598            91522.0       54.94

In [37]:
pd.read_sql("""
SELECT 
    SUM(CASE 
        WHEN Tenure < 12 
        OR `Payment Delay` > 5 
        OR `Usage Frequency` < 20 
        OR `Support Calls` > 10 
        THEN `Total Spend` ELSE 0 END) AS revenue_at_risk,

    SUM(`Total Spend`) AS total_revenue,

    ROUND(
        SUM(CASE 
            WHEN Tenure < 12 
            OR `Payment Delay` > 5 
            OR `Usage Frequency` < 20 
            OR `Support Calls` > 10 
            THEN `Total Spend` ELSE 0 END)
        / SUM(`Total Spend`) * 100, 2
    ) AS risk_percentage

FROM churn_data
WHERE `Total Spend` IS NOT NULL
""", engine)

   revenue_at_risk  total_revenue  risk_percentage
0     2.573820e+08   2.784366e+08            92.44

In [38]:
pd.read_sql("""
SELECT 
    `Subscription Type`,
    SUM(`Total Spend`) AS revenue_lost,
    COUNT(*) AS churned_customers
FROM churn_data
WHERE Churn = 1
AND `Total Spend` IS NOT NULL
GROUP BY `Subscription Type`
ORDER BY revenue_lost DESC
""", engine)

  Subscription Type  revenue_lost  churned_customers
0          Standard   45275783.20              83616
1             Basic   45078423.15              83210
2           Premium   44966634.25              83173

In [39]:
pd.read_sql("""
SELECT 
    SUM(CASE WHEN Churn = 1 THEN `Total Spend` ELSE 0 END) AS churned_revenue,
    SUM(`Total Spend`) AS total_revenue,
    ROUND(
        SUM(CASE WHEN Churn = 1 THEN `Total Spend` ELSE 0 END) 
        / SUM(`Total Spend`) * 100, 2
    ) AS churn_revenue_percentage
FROM churn_data
WHERE `Total Spend` IS NOT NULL
""", engine)

   churned_revenue  total_revenue  churn_revenue_percentage
0     1.353208e+08   2.784366e+08                      48.6

In [40]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN Tenure < 12 THEN 'New Customers'
        ELSE 'Old Customers'
    END AS customer_type,

    COUNT(*) AS total_customers,

    SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) AS churned_customers,

    ROUND(
        SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2
    ) AS churn_rate

FROM churn_data
WHERE Churn IS NOT NULL
GROUP BY customer_type
""", engine)

   customer_type  total_customers  churned_customers  churn_rate
0  Old Customers           362336           204113.0       56.33
1  New Customers            78496            45886.0       58.46

In [41]:
pd.read_sql("""
SELECT COUNT(*) AS high_risk_customers
FROM (
    SELECT 
        (CASE WHEN Tenure < 12 THEN 1 ELSE 0 END +
         CASE WHEN `Payment Delay` > 5 THEN 1 ELSE 0 END +
         CASE WHEN `Usage Frequency` < 20 THEN 1 ELSE 0 END +
         CASE WHEN `Support Calls` > 10 THEN 1 ELSE 0 END
        ) AS risk_score
    FROM churn_data
) t
WHERE risk_score >= 3
""", engine)

   high_risk_customers
0                38481

In [43]:
pd.read_sql("""
SELECT 
    SUM(`Total Spend`) AS high_risk_revenue
FROM (
    SELECT 
        `Total Spend`,
        (CASE WHEN Tenure < 12 THEN 1 ELSE 0 END +
         CASE WHEN `Payment Delay` > 5 THEN 1 ELSE 0 END +
         CASE WHEN `Usage Frequency` < 20 THEN 1 ELSE 0 END +
         CASE WHEN `Support Calls` > 10 THEN 1 ELSE 0 END
        ) AS risk_score
    FROM churn_data
) t
WHERE risk_score >= 3
""", engine)

   high_risk_revenue
0        23948639.51

In [44]:
pd.read_sql("""
SELECT COUNT(*) AS total_customers
FROM churn_data
""", engine)

   total_customers
0           440833